### ISSUE TITLE
 /lib/modules/4.19.75+/build: No such file or directory.  Stop.

### ISSUE THREAD

**Issue by 6bigfire** [julbouln/tinydrm_it8951#1]
I have got the errors when i made it.
Can you help me?

`pi@raspberrypi:~/tinydrm_it8951 $ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: *** /lib/modules/4.19.75+/build: No such file or directory.  Stop.
make: *** [Makefile:4: default] Error 2
`

**Comment by julbouln** [comment]
Hi,
Did you install kernel headers ? https://www.raspberrypi.org/documentation/linux/kernel/headers.md

**Comment by 6bigfire** [comment]
I have not installed the kernel headers！Thank you very much， I'll try it.

**Comment by 6bigfire** [comment]
OK，I have not installed it. Thank you!

**Comment by 6bigfire** [comment]
OK!

pi@raspberrypi:~/tinydrm_it8951 $ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-4.19.75+'
  CC [M]  /home/pi/tinydrm_it8951/it8951.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/pi/tinydrm_it8951/it8951.mod.o
  LD [M]  /home/pi/tinydrm_it8951/it8951.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.19.75+'
