### ISSUE TITLE
Moving to higher resolution it8951-driven panels

### ISSUE THREAD

**Issue by HeathenUK** [julbouln/tinydrm_it8951#4]
I've recently purchased a newer, higher resolution 6 inch panel to replace the 800x600 panel.

As far as I can tell looking at reference materials, the LUT constants etc. are the same between the panels and although the IT8951 board is badged as "IT8951 (B)" (and has a higher pin count on the ribbon) it also appears to follow the same reference specs and TCON commands etc.

When I swap the old panel (and driver board) for the new I get the 800x600 framebuffer mashed into one corner.

I can see a single place where the resolution is hardcoded in it8951.c. If I adjust that, I lose all picture entirely.

Any thoughts on whether there's anything else that will be hardcoding the driver to the old panel or the old resolution?

**Comment by julbouln** [comment]
I'm afraid you won't be able to do that easily. I think the chip actually includes a special firmware specifically programmed for each screen model. I asked Waveshare for more information about that firmware but they refused to give me more than what they already provide, I suspect they have some NDA with ITE tech which forbid them to do that.

**Comment by HeathenUK** [comment]
Good to know, thanks!

It's a pity, clearly there are other solutions to workaround depending on the project but none as elegant and generally-applicable as integrating the panel into a /dev/fbX!
